//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRID 4x3
        ///
        ///1 1 E
        ///RFR
        ///1 0 W
        ///
        ///1 1 E
        ///RFRF
        ///1 1 E
        ///
        ///1 1 E
        ///RFF
        ///1 1 E.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRID 40x40
        ///
        ///1 1 E
        ///RFRFRFRF
        ///1 1 E
        ///
        ///3 2 N
        ///FRRFLLFFRRFLL
        ///3 3 N
        ///
        ///0 3 W
        ///LLFFFLFLFL
        ///2 4 S.
        /// </summary>
        public static string Sample1 {
            get {
                return ResourceManager.GetString("Sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRID 20x20
        ///
        ///OBSTACLE 1 2
        ///OBSTACLE 1 3
        ///OBSTACLE 2 4
        ///
        ///1 1 E
        ///RFRFRFRF
        ///1 1 E
        ///
        ///3 2 N
        ///FRRFLLFFRRFLL
        ///3 3 N
        ///
        ///0 3 W
        ///LLFFFLFLFL
        ///2 4 S.
        /// </summary>
        public static string Sample2 {
            get {
                return ResourceManager.GetString("Sample2", resourceCulture);
            }
        }
    }
}
